language: generic
sudo: required
dist: trusty

# branch "tested" is only commits which were already tested on master, no need to test again
branches:
  except:
  - tested
  - live_verification

matrix:
  fast_finish: true
  include:
    - env: COQ_VERSION="master" COQ_PACKAGE="coq libcoq-ocaml-dev" PPA="ppa:jgross-h/coq-master-daily"
    - env: COQ_VERSION="v8.12"  COQ_PACKAGE="coq"                  PPA="ppa:jgross-h/coq-8.12-daily"
    - env: COQ_VERSION="8.12.0" COQ_PACKAGE="coq-8.12.0"           PPA="ppa:jgross-h/many-coq-versions-ocaml-4-05"

before_install:
  - if [ ! -z "$PPA" ]; then sudo add-apt-repository "$PPA" -y; fi
  - travis_retry ./etc/ci/sudo-apt-get-update.sh -q
  - travis_retry sudo apt-get install $COQ_PACKAGE -y --allow-unauthenticated

# script: TIMED=1 TRY_MANGLE_NAMES=1 make -j2 && ./manglenames-stats.sh

script: TIMED=1 make
