on:
  schedule:
    # run at 06:59 UTC each day
    - cron:  '59 6 * * *'

jobs:
  updateBranch:
    runs-on: ubuntu-latest
    name: WIP
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'tested'
        fetch-depth: 0
    - run: pwd
    - uses: samuelgruetter/check-ci-success@master
      with:
        repo_owner: 'mit-plv'
        repo_name: 'bedrock2'
        branch_name: 'master'
        check_name: 'build (master, coq libcoq-ocaml-dev, ppa:jgross-h/coq-master-daily)'
    - run: echo "This step runs after the python script"
    - run: git fetch origin master
    - run: git log --oneline --max-count=10
    - run: git merge --ff-only remotes/origin/master
    - run: git log --oneline --max-count=10
    - run: git push
